version: '3.8'

services:
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate  &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/scr/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data: